/**
 * What the page can tell us about study-language captions on the current video.
 *
 * On a clip with no usable Japanese captions, cards simply stopped appearing
 * while Listening Mode could still look active, so the extension read as
 * broken (issue #128). Adapters report what they found here, the content script
 * turns a "missing" report into one on-screen explanation per video, and the
 * popup reads the same state for its status row.
 */

export type CaptionState = "unknown" | "ok" | "missing";

/** Why the study-language captions are unusable, for the notice copy. */
export type CaptionMissingReason =
  | "no-track" // the video lists no track in the study language
  | "empty-track"; // a track is listed but fetched empty or unparseable

export interface CaptionReport {
  state: CaptionState;
  /** Language we needed, not what the video has. */
  lang: "ja" | "en";
  reason?: CaptionMissingReason;
  /** Auto-generated tracks are usable but worth naming in the popup. */
  autoGenerated?: boolean;
}

const UNKNOWN: CaptionReport = { state: "unknown", lang: "ja" };

let current: CaptionReport = UNKNOWN;
const listeners = new Set<(report: CaptionReport) => void>();

export function reportCaptions(report: CaptionReport): void {
  const same =
    current.state === report.state &&
    current.lang === report.lang &&
    current.reason === report.reason &&
    !!current.autoGenerated === !!report.autoGenerated;
  current = report;
  if (same) return;
  for (const listener of listeners) {
    try {
      listener(report);
    } catch {
      /* a listener must never break caption detection */
    }
  }
}

export function captionReport(): CaptionReport {
  return current;
}

/** Called on every video change: nothing is known about the new video yet. */
export function resetCaptions(): void {
  reportCaptions(UNKNOWN);
}

export function onCaptions(listener: (report: CaptionReport) => void): void {
  listeners.add(listener);
}

const LANG_NAME: Record<"ja" | "en", string> = { ja: "Japanese", en: "English" };

/**
 * The on-screen explanation for a video with no usable captions, or null when
 * there is nothing worth saying.
 *
 * Silent when Listening Mode is already running: that IS the fallback, and a
 * notice telling a learner to turn on what they just turned on reads as a bug.
 * Silent too when the learner has both automatic cards and Subtitle Lens off,
 * since neither was going to produce anything from captions anyway.
 */
export function captionNoticeText(
  report: CaptionReport,
  opts: { listening: boolean; cardsOn: boolean; lensOn: boolean }
): string | null {
  if (report.state !== "missing") return null;
  if (opts.listening) return null;
  if (!opts.cardsOn && !opts.lensOn) return null;
  const lang = LANG_NAME[report.lang];
  return (
    `No ${lang} captions on this video, so there are no words to pull from the subtitles. ` +
    `Start Listening Mode from the AnimeVocab toolbar icon to learn from the audio instead, ` +
    `or pick a video that offers ${lang} subtitles.`
  );
}

/** Short status for the popup's card row. Null keeps the row's normal detail. */
export function captionStatusDetail(report: CaptionReport): string | null {
  if (report.state === "missing") {
    return `No ${LANG_NAME[report.lang]} captions on this video. Listening Mode still works.`;
  }
  if (report.state === "ok" && report.autoGenerated) {
    return `Using auto-generated ${LANG_NAME[report.lang]} captions on this video.`;
  }
  return null;
}
