import { beforeEach, describe, expect, it, vi } from "vitest";
import {
  captionNoticeText,
  captionReport,
  captionStatusDetail,
  onCaptions,
  reportCaptions,
  resetCaptions,
} from "../src/lib/caption-status";

// Issue #128: on a clip with no usable Japanese captions, cards silently
// stopped appearing while Listening Mode could still look active.
describe("caption status", () => {
  beforeEach(() => resetCaptions());

  it("starts out knowing nothing", () => {
    expect(captionReport().state).toBe("unknown");
  });

  it("notifies listeners only when the report actually changes", () => {
    const seen = vi.fn();
    onCaptions(seen);
    reportCaptions({ state: "missing", lang: "ja", reason: "no-track" });
    reportCaptions({ state: "missing", lang: "ja", reason: "no-track" });
    expect(seen).toHaveBeenCalledTimes(1);
    reportCaptions({ state: "ok", lang: "ja" });
    expect(seen).toHaveBeenCalledTimes(2);
  });

  it("keeps reporting after a listener throws", () => {
    onCaptions(() => {
      throw new Error("listener exploded");
    });
    const ok = vi.fn();
    onCaptions(ok);
    expect(() => reportCaptions({ state: "missing", lang: "ja" })).not.toThrow();
    expect(ok).toHaveBeenCalledOnce();
    expect(captionReport().state).toBe("missing");
  });

  it("resets to unknown for the next video", () => {
    reportCaptions({ state: "ok", lang: "ja" });
    resetCaptions();
    expect(captionReport().state).toBe("unknown");
  });
});

describe("captionNoticeText", () => {
  const on = { listening: false, cardsOn: true, lensOn: true };

  it("explains missing captions and points at Listening Mode", () => {
    const text = captionNoticeText({ state: "missing", lang: "ja", reason: "no-track" }, on);
    expect(text).toContain("No Japanese captions");
    expect(text).toContain("Listening Mode");
  });

  it("names the language the learner is actually studying", () => {
    const text = captionNoticeText({ state: "missing", lang: "en" }, on);
    expect(text).toContain("No English captions");
  });

  it("says nothing while captions are fine or unknown", () => {
    expect(captionNoticeText({ state: "ok", lang: "ja" }, on)).toBeNull();
    expect(captionNoticeText({ state: "unknown", lang: "ja" }, on)).toBeNull();
  });

  // Telling someone to start what they already started reads as a bug.
  it("says nothing when Listening Mode is already covering for the captions", () => {
    expect(
      captionNoticeText({ state: "missing", lang: "ja" }, { ...on, listening: true })
    ).toBeNull();
  });

  it("says nothing when neither cards nor the Lens would have read captions", () => {
    expect(
      captionNoticeText({ state: "missing", lang: "ja" }, { listening: false, cardsOn: false, lensOn: false })
    ).toBeNull();
    // Either one alone is still a reason to explain the silence.
    expect(
      captionNoticeText({ state: "missing", lang: "ja" }, { listening: false, cardsOn: false, lensOn: true })
    ).not.toBeNull();
    expect(
      captionNoticeText({ state: "missing", lang: "ja" }, { listening: false, cardsOn: true, lensOn: false })
    ).not.toBeNull();
  });

  it("never uses long dashes in learner-facing copy", () => {
    const texts = [
      captionNoticeText({ state: "missing", lang: "ja" }, on),
      captionStatusDetail({ state: "missing", lang: "ja" }),
      captionStatusDetail({ state: "ok", lang: "ja", autoGenerated: true }),
    ];
    for (const text of texts) {
      expect(text).toBeTruthy();
      expect(text!).not.toMatch(/[—–]/);
    }
  });
});

describe("captionStatusDetail", () => {
  it("tells the popup what stopped, and that Listening still works", () => {
    const detail = captionStatusDetail({ state: "missing", lang: "ja", reason: "empty-track" });
    expect(detail).toContain("No Japanese captions");
    expect(detail).toContain("Listening Mode");
  });

  it("flags auto-generated captions, and stays quiet on clean ones", () => {
    expect(captionStatusDetail({ state: "ok", lang: "ja", autoGenerated: true })).toContain(
      "auto-generated"
    );
    expect(captionStatusDetail({ state: "ok", lang: "ja" })).toBeNull();
    expect(captionStatusDetail({ state: "unknown", lang: "ja" })).toBeNull();
  });
});
