// Collectible card system. XP is derived deterministically from the user's
// sync snapshot (words, reviews, watch time), so there's no server state to
// migrate — the collection recomputes anywhere the snapshot lives.
//
// 60 cards across 15 anime STYLE_FAMILIES (4 each). Every character is
// ORIGINAL (archetypes, never a real/licensed character); families describe an
// art *style* only. Art is generated by scripts/generate-cards.mjs into
// /public/cards/<id>.png and registered in cards-art.ts. See docs/anime-cards.md.

export type Rarity = "N" | "R" | "SR" | "SSR" | "UR";
export type StyleKey =
  | "slayer" | "titan" | "reaper" | "spirit" | "curse"
  | "voyage" | "lunar" | "neon" | "hearth" | "psyche"
  | "mecha" | "horizon" | "pocket" | "eclipse" | "chibi";

export interface StyleFamily {
  label: string;
  /** Art-direction block fed verbatim to the image model. */
  style: string;
  /** Brand-free rephrase used when the named-franchise prompt trips the image
   * model's moderation (some trademarks are blocked). Optional. */
  styleSafe?: string;
}

// Style descriptions reference well-known anime as *visual style* cues only.
export const STYLE_FAMILIES: Record<StyleKey, StyleFamily> = {
  slayer: {
    label: "Taisho Blade",
    style:
      "Art style inspired by Demon Slayer (Ufotable): Taisho-era Japan, patterned haori kimono, ukiyo-e-influenced water and flame effect patterns, bold confident sumi outlines, painterly digital cel shading, rich saturated color.",
  },
  titan: {
    label: "Last Wall",
    style:
      "Art style inspired by Attack on Titan (WIT/MAPPA): gritty semi-realistic proportions, muted desaturated palette, heavy detailed linework and crosshatched shadow, military survey-corps cloaks and gear, ominous scale and tension.",
  },
  reaper: {
    label: "Soul Fashion",
    style:
      "Art style inspired by Bleach (Tite Kubo): sleek high-fashion character design, sharp angular features, flowing black robes, stark high-contrast with a single bold spot color, cool confident pose, minimal negative-space background.",
    styleSafe:
      "Sleek modern shonen art style: high-fashion angular character design, flowing black robes and sashes, stark high-contrast inking with a single bold spot color, cool confident pose, minimal negative-space background.",
  },
  spirit: {
    label: "Wind Valley",
    style:
      "Art style inspired by Studio Ghibli: soft hand-painted watercolor look, gentle rounded faces with simple warm expressions, pastoral earthy palette, whimsical and cozy, painterly skies and foliage.",
  },
  curse: {
    label: "Cursed Hour",
    style:
      "Art style inspired by Jujutsu Kaisen (MAPPA): modern urban shonen, dark swirling cursed-energy smoke effects, sharp contemporary uniforms and streetwear, moody high-contrast lighting, kinetic.",
  },
  voyage: {
    label: "Grand Voyage",
    style:
      "Art style inspired by One Piece (Eiichiro Oda): exaggerated cartoony proportions, thick bold outlines, bright saturated adventurous colors, expressive rubbery dynamic pose, playful.",
    styleSafe:
      "Classic pirate-adventure shonen art style: exaggerated cartoony proportions, thick bold outlines, bright saturated colors, expressive dynamic rubbery pose, playful high-seas energy.",
  },
  lunar: {
    label: "Moon Prism",
    style:
      "Art style inspired by 90s magical-girl shoujo (Sailor Moon): sparkles and twinkling stars, soft pastel palette, large glittering eyes with big highlights, flowing ribbons and frills, retro hand-cel finish.",
  },
  neon: {
    label: "Night City",
    style:
      "Art style inspired by Cyberpunk Edgerunners (Studio Trigger): bold saturated neon palette, kinetic exaggerated shapes, subtle glitch accents, cyberpunk streetwear and chrome augmetics, high energy.",
  },
  hearth: {
    label: "Warm Hearth",
    style:
      "Art style inspired by Spy x Family (CloverWorks): clean warm modern anime, soft rounded friendly design, cozy domestic charm, gentle even shading, wholesome and inviting.",
  },
  psyche: {
    label: "Mind Static",
    style:
      "Art style inspired by Mob Psycho 100 (Bones): loose expressive sketchy linework, bold psychedelic swirling patterns, flat punchy colors, minimalist background, surreal calm energy.",
  },
  mecha: {
    label: "Eva Test",
    style:
      "Art style inspired by 90s Neon Genesis Evangelion (Gainax): retro mecha-era cel animation, clinical framing, muted teal and orange palette, plugsuits and stark cross motifs, unsettling stillness.",
  },
  horizon: {
    label: "Bright Sky",
    style:
      "Art style inspired by Makoto Shinkai (Your Name): hyper-detailed luminous lighting, brilliant vivid skies with volumetric clouds, gentle lens flare, photoreal painted backgrounds behind soft anime characters, emotional.",
    styleSafe:
      "Modern cinematic anime art style: hyper-detailed luminous lighting, brilliant vivid skies with volumetric clouds, gentle lens flare, lushly painted realistic backgrounds behind soft anime characters, emotional.",
  },
  pocket: {
    label: "Pocket Pals",
    style:
      "Art style inspired by Pokemon (Ken Sugimori): friendly bright creature-companion design, clean rounded shapes, cheerful gouache-watercolor coloring, adventurous kid-and-companion energy. Include a small original creature companion beside the character.",
    styleSafe:
      "Bright friendly monster-collector art style: clean rounded shapes, cheerful gouache-watercolor coloring, an adventurous kid alongside a small original cartoon creature companion, wholesome energy.",
  },
  eclipse: {
    label: "Black Eclipse",
    style:
      "Art style inspired by Berserk dark fantasy (Kentaro Miura): dense heavy ink hatching, gothic ornate armor, dramatic chiaroscuro, grim medieval mood, intricate rendered detail.",
  },
  chibi: {
    label: "Tiny Squad",
    style:
      "Super-deformed chibi anime style: tiny cute proportions, oversized head, big simple sparkly eyes, minimal clean shapes, soft pastel palette, adorable and playful.",
  },
};

export interface CardDef {
  id: string;
  /** Original character name (no licensed characters — copyright-safe). */
  name: string;
  /** Kanji motif used as the placeholder art + the card's "element". */
  kanji: string;
  reading: string;
  epithet: string;
  rarity: Rarity;
  /** Level at which the card unlocks. */
  level: number;
  /** Which art-style family to render this card in. */
  style: StyleKey;
  /** Visual description consumed by scripts/generate-cards.mjs (art prompts). */
  look: string;
  /** Path to real art under /public. Resolved from CARD_ART (cards-art.ts,
   * auto-managed by the generator) at render time in cards-panel. */
  art?: string;
}

export const MAX_LEVEL = 50;

// Cumulative XP needed to *reach* level n (level 1 = 0).
export function xpForLevel(n: number): number {
  const clamped = Math.max(1, Math.min(MAX_LEVEL, Math.floor(n)));
  return 40 * (clamped - 1) * clamped;
}

export function computeXp(input: {
  totalWords: number;
  judgedCards: number;
  watchMinutes: number;
  streakLongest: number;
}): number {
  return (
    input.totalWords * 12 +
    input.judgedCards * 6 +
    input.watchMinutes * 3 +
    input.streakLongest * 25
  );
}

const RANKS: [number, string, string][] = [
  [1, "見習い", "Apprentice"],
  [5, "旅人", "Traveler"],
  [10, "剣士", "Swordfighter"],
  [18, "侍", "Samurai"],
  [28, "師匠", "Master"],
  [40, "伝説", "Legend"],
];

export interface LevelState {
  xp: number;
  level: number;
  rankKanji: string;
  rankName: string;
  intoLevel: number;
  forNext: number;
}

export function levelState(xp: number): LevelState {
  let level = 1;
  while (level < MAX_LEVEL && xp >= xpForLevel(level + 1)) level++;
  const floor = xpForLevel(level);
  const ceil = level >= MAX_LEVEL ? floor : xpForLevel(level + 1);
  const rank = [...RANKS].reverse().find(([min]) => level >= min) ?? RANKS[0];
  return {
    xp,
    level,
    rankKanji: rank[1],
    rankName: rank[2],
    intoLevel: xp - floor,
    forNext: Math.max(1, ceil - floor),
  };
}

// 60 cards, grouped by style family (4 each). Level = unlock order; rarity
// roughly climbs with level. Display groups by family so the collection reads
// as style "sets".
export const CARDS: CardDef[] = [
  // — slayer —
  { id: "sl_honoka", name: "Honoka", kanji: "炎", reading: "ほのお", epithet: "Ember of the First Breath", rarity: "N", level: 1, style: "slayer", look: "young swordfighter girl in a flame-patterned haori, hair tied back, gripping a nichirin katana, small embers drifting" },
  { id: "sl_mizuho", name: "Mizuho", kanji: "水", reading: "みず", epithet: "Tide of the Tenth Form", rarity: "R", level: 17, style: "slayer", look: "calm swordsman mid-stance releasing a stylized wave of water, dark uniform under a striped haori, wet hair" },
  { id: "sl_kagura", name: "Kagura", kanji: "鈴", reading: "すず", epithet: "Bell of the Broken Moon", rarity: "SR", level: 34, style: "slayer", look: "masked demon-hunter with a bell earring, twin short blades crossed, moonlit, patterned kimono sleeves torn" },
  { id: "sl_akatsuki", name: "Akatsuki", kanji: "暁", reading: "あかつき", epithet: "Dawn That Ends the Night", rarity: "SSR", level: 49, style: "slayer", look: "regal swordmaster wreathed in intertwining flame and water dragons, ornate haori, dramatic sunrise" },

  // — titan —
  { id: "ti_reiner", name: "Sasel", kanji: "壁", reading: "かべ", epithet: "Watcher on the Wall", rarity: "N", level: 2, style: "titan", look: "grim young scout in survey-corps jacket and ODM gear straps, wind-blown cloak, standing atop a stone wall" },
  { id: "ti_hana", name: "Hana", kanji: "翼", reading: "つばさ", epithet: "Wings of Freedom", rarity: "R", level: 18, style: "titan", look: "determined soldier girl mid-swing on maneuver-gear cables, cloak flaring, gritted teeth" },
  { id: "ti_grim", name: "Volk", kanji: "巨", reading: "きょ", epithet: "The Nape-Cutter", rarity: "SR", level: 35, style: "titan", look: "scarred veteran commander, one arm bandaged, drawing dual blades, ruined city behind, storm clouds" },
  { id: "ti_founder", name: "Ymir-less", kanji: "礎", reading: "いしずえ", epithet: "First of the Founding", rarity: "SSR", level: 50, style: "titan", look: "towering armored colossal figure of steam and muscle looming behind a tiny cloaked soldier, apocalyptic" },

  // — reaper —
  { id: "re_kuro", name: "Kurogane", kanji: "斬", reading: "ざん", epithet: "Blade in Black", rarity: "N", level: 3, style: "reaper", look: "cool teen soul-reaper in a flowing black robe, oversized cleaver sword resting on shoulder, spiked hair" },
  { id: "re_yuki", name: "Yukihime", kanji: "氷", reading: "こおり", epithet: "Frost Ceremony", rarity: "R", level: 19, style: "reaper", look: "elegant ice-wielding reaper woman, white sash, releasing crystalline petals, serene sharp eyes" },
  { id: "re_zangetsu", name: "Getsuei", kanji: "月", reading: "つき", epithet: "Moonfang Released", rarity: "SR", level: 36, style: "reaper", look: "battle-worn reaper with a torn black coat and a massive crescent blade, spiral of dark energy, one glowing eye" },
  { id: "re_king", name: "Reiou", kanji: "霊", reading: "れい", epithet: "The Spirit Throne", rarity: "SSR", level: 48, style: "reaper", look: "godlike robed figure fractured into shards of light on a black void, ornate high collar, single vermillion accent" },

  // — spirit (ghibli) —
  { id: "sp_totomi", name: "Totomi", kanji: "森", reading: "もり", epithet: "Friend of the Cedar", rarity: "N", level: 1, style: "spirit", look: "small round forest spirit with a leaf on its head standing in tall grass beside a curious child in a sun hat" },
  { id: "sp_umi", name: "Umi", kanji: "海", reading: "うみ", epithet: "Girl of the Tide Pools", rarity: "N", level: 12, style: "spirit", look: "cheerful barefoot girl in a red dress running along a seaside cliff, wind in her hair, gulls overhead" },
  { id: "sp_kama", name: "Kama-jii", kanji: "湯", reading: "ゆ", epithet: "Keeper of the Bathhouse", rarity: "R", level: 26, style: "spirit", look: "kindly whiskered old spirit with many arms tending a warm bathhouse boiler, steam curling, lanterns" },
  { id: "sp_ohtori", name: "Ohtori", kanji: "空", reading: "そら", epithet: "Rider of the Sky Current", rarity: "SR", level: 43, style: "spirit", look: "girl gliding on a great white feathered creature above painted valleys and cloud seas, joyful" },

  // — curse (jjk) —
  { id: "cu_rei", name: "Rei", kanji: "呪", reading: "のろい", epithet: "First-Year Prodigy", rarity: "N", level: 4, style: "curse", look: "hooded student sorcerer with wrapped hands, dark smoke curling from a fist, confident smirk, school uniform" },
  { id: "cu_maki", name: "Maki", kanji: "刃", reading: "は", epithet: "Cursed-Tool Bearer", rarity: "R", level: 20, style: "curse", look: "athletic fighter in glasses swinging a cursed polearm, tracksuit, energy trailing the blade" },
  { id: "cu_domain", name: "Ankoku", kanji: "domain", reading: "りょういき", epithet: "Domain Unfolded", rarity: "SR", level: 37, style: "curse", look: "sorcerer with hands in a mudra summoning an inky expanding domain sphere, floating debris, glowing eyes" },
  { id: "cu_king", name: "Ryomen", kanji: "災", reading: "わざわい", epithet: "The Calamity Reborn", rarity: "SSR", level: 49, style: "curse", look: "four-armed markings-covered cursed king grinning, black tendrils, oppressive aura, torn cityscape" },

  // — voyage (one piece) —
  { id: "vo_luka", name: "Luka", kanji: "夢", reading: "ゆめ", epithet: "Captain of the Straw Fleet", rarity: "N", level: 2, style: "voyage", look: "grinning rubber-limbed boy captain in a straw hat and open vest, one arm stretched cartoonishly, ocean breeze" },
  { id: "vo_nami", name: "Kaji", kanji: "羅", reading: "ら", epithet: "Reader of the Log Pose", rarity: "N", level: 13, style: "voyage", look: "clever navigator girl holding a glowing compass and a rolled map, coin belt, confident wink" },
  { id: "vo_zoro", name: "Mikazuki", kanji: "刀", reading: "かたな", epithet: "Three-Blade Swordsman", rarity: "R", level: 27, style: "voyage", look: "muscular swordsman with a green haramaki holding three katana (one in mouth), scar over eye, bold stance" },
  { id: "vo_yonko", name: "Beckett", kanji: "覇", reading: "は", epithet: "Emperor of the New Sea", rarity: "SR", level: 44, style: "voyage", look: "enormous laughing pirate emperor with a giant coat over the shoulders, tiny ship in one hand, storm sky" },

  // — lunar (sailor moon) —
  { id: "lu_hoshimi", name: "Hoshimi", kanji: "星", reading: "ほし", epithet: "Guardian of the Waxing Star", rarity: "N", level: 3, style: "lunar", look: "magical girl in a sailor-style fuku with star hairpins mid-transformation, ribbons and sparkles swirling" },
  { id: "lu_tsukina", name: "Tsukina", kanji: "月", reading: "つき", epithet: "Moonlight Tiara", rarity: "N", level: 14, style: "lunar", look: "twin-tailed heroine raising a glowing crescent wand, tiara gleaming, pastel light rays, hearts" },
  { id: "lu_venus", name: "Kanae", kanji: "愛", reading: "あい", epithet: "Chain of the Evening Star", rarity: "R", level: 28, style: "lunar", look: "confident magical girl swinging a glittering heart-chain whip, orange bow, dramatic wink, sparkles" },
  { id: "lu_queen", name: "Serenia", kanji: "后", reading: "きさき", epithet: "The Silver Millennium", rarity: "SSR", level: 48, style: "lunar", look: "ethereal moon queen in a flowing white gown with a crescent crown, silver hair to the floor, cosmic halo" },

  // — neon (edgerunners) —
  { id: "ne_spike", name: "Spike", kanji: "電", reading: "でん", epithet: "Runner on the Wire", rarity: "N", level: 5, style: "neon", look: "cocky street runner in a neon bomber jacket with chrome arm, headphones, glitchy motion trail, night alley" },
  { id: "ne_rebel", name: "Nyx", kanji: "夜", reading: "よる", epithet: "Queen of the Night Market", rarity: "R", level: 21, style: "neon", look: "punk woman with cyber-optics and pink undercut, holding a glowing pistol, neon signs bokeh behind" },
  { id: "ne_ghost", name: "Zero", kanji: "零", reading: "れい", epithet: "The Netrunner", rarity: "SR", level: 38, style: "neon", look: "hooded hacker plugged into cables, holographic code cascading around, face lit by screen glow" },
  { id: "ne_titan", name: "Maxx", kanji: "鋼", reading: "はがね", epithet: "Full-Chrome Legend", rarity: "SSR", level: 50, style: "neon", look: "hulking fully-cyborg mercenary with glowing core, wielding a massive rail weapon, city exploding in neon" },

  // — hearth (spy x family) —
  { id: "he_anya", name: "Ani", kanji: "心", reading: "こころ", epithet: "The Little Telepath", rarity: "N", level: 4, style: "hearth", look: "tiny wide-eyed girl with pointed hair-buns making an excited face, oversized school coat, peanut in hand" },
  { id: "he_loid", name: "Twiley", kanji: "父", reading: "ちち", epithet: "Master of Disguise", rarity: "N", level: 15, style: "hearth", look: "sharp-dressed spy dad adjusting a tie with a warm reluctant smile, half-hidden earpiece, cozy home light" },
  { id: "he_yor", name: "Iris", kanji: "刺", reading: "し", epithet: "The Thorn Homemaker", rarity: "R", level: 29, style: "hearth", look: "elegant woman in an apron over an assassin's dress, holding a ladle and a hidden dagger, gentle blush" },
  { id: "he_bond", name: "Pom", kanji: "予", reading: "よ", epithet: "The Precognitive Pup", rarity: "SR", level: 42, style: "hearth", look: "big fluffy white dog with a wise expression sitting proudly, tiny cape, cozy living-room background" },

  // — psyche (mob psycho) —
  { id: "ps_mob", name: "Kage", kanji: "気", reading: "き", epithet: "100% Percent", rarity: "N", level: 6, style: "psyche", look: "plain bowl-cut boy standing calmly as psychedelic aura swirls explode behind him, blank expression" },
  { id: "ps_dimple", name: "Ekubo", kanji: "霊", reading: "れい", epithet: "The Wandering Spirit", rarity: "N", level: 16, style: "psyche", look: "floating green blob spirit with a smug grin swirling around a deadpan kid, loose sketchy lines" },
  { id: "ps_reigen", name: "Serizen", kanji: "師", reading: "し", epithet: "Greatest Con of the Century", rarity: "R", level: 30, style: "psyche", look: "confident suited fake-psychic striking a dramatic pointing pose, salt in hand, sparkle of pure bluff" },
  { id: "ps_awaken", name: "Kage △", kanji: "覚", reading: "かく", epithet: "The Awakening", rarity: "SR", level: 45, style: "psyche", look: "boy dissolving into swirling cosmic psychic energy, body outlined in light, reality warping, surreal" },

  // — mecha (eva) —
  { id: "me_shin", name: "Ren", kanji: "使", reading: "し", epithet: "Third Pilot", rarity: "N", level: 7, style: "mecha", look: "anxious teen pilot in a teal-and-white plugsuit, neural clips in hair, clinical cockpit glow, muted tones" },
  { id: "me_asuka", name: "Rika", kanji: "紅", reading: "べに", epithet: "Second of the Red Unit", rarity: "R", level: 22, style: "mecha", look: "fierce pilot girl in a red plugsuit, interface headset, arms crossed, orange warning lights" },
  { id: "me_unit", name: "Unit-00", kanji: "零", reading: "れい", epithet: "Test Type, Sync 400", rarity: "SR", level: 39, style: "mecha", look: "hulking humanoid bio-mecha head and shoulders with a single glowing eye, restraint armor, cross-shaped blast behind" },
  { id: "me_angel", name: "Sachiel", kanji: "神", reading: "かみ", epithet: "The Descended Pattern", rarity: "SSR", level: 47, style: "mecha", look: "geometric masked angelic entity with a glowing core and cross-shaped light, floating, eerie symmetry" },

  // — horizon (shinkai) —
  { id: "ho_taki", name: "Sora", kanji: "空", reading: "そら", epithet: "Between Two Skies", rarity: "N", level: 8, style: "horizon", look: "student on a hilltop at golden hour gazing up, brilliant painted clouds and lens flare, uniform, wistful" },
  { id: "ho_mitsu", name: "Yuna", kanji: "糸", reading: "いと", epithet: "Braided Fate", rarity: "R", level: 23, style: "horizon", look: "girl holding a red braided cord against a vivid twilight sky full of stars and a comet streak" },
  { id: "ho_rain", name: "Ame", kanji: "雨", reading: "あめ", epithet: "The Weather Child", rarity: "SR", level: 40, style: "horizon", look: "girl reaching up as sunlight breaks through storm clouds, rain droplets sparkling, luminous rays, rooftop" },
  { id: "ho_comet", name: "Suisei", kanji: "彗", reading: "すい", epithet: "The Once-in-1200-Years", rarity: "SSR", level: 46, style: "horizon", look: "two tiny silhouettes on a ridge beneath an enormous glowing comet splitting a jewel-toned night sky" },

  // — pocket (pokemon) —
  { id: "po_satoru", name: "Kai", kanji: "友", reading: "とも", epithet: "The Rookie Explorer", rarity: "N", level: 9, style: "pocket", look: "cheerful kid adventurer in a cap and backpack waving hello, a small original round spark-tailed cartoon creature perched happily on their shoulder, sunny meadow" },
  { id: "po_flame", name: "Emberling", kanji: "火", reading: "ひ", epithet: "Little Ember", rarity: "N", level: 17, style: "pocket", look: "cute original fox-like fire creature with a flame-tipped tail, big friendly eyes, meadow, watercolor" },
  { id: "po_aqua", name: "Tidepup", kanji: "波", reading: "なみ", epithet: "Tide Companion", rarity: "R", level: 31, style: "pocket", look: "round original water-otter creature riding a small wave, splashing happily, seashell on its head" },
  { id: "po_legend", name: "Raijuu", kanji: "雷", reading: "らい", epithet: "The Storm Legendary", rarity: "SR", level: 45, style: "pocket", look: "majestic original electric beast-dragon with crackling mane, roaring atop a cliff, thunderclouds, dramatic" },

  // — eclipse (berserk) —
  { id: "ec_guts", name: "Grendel", kanji: "剣", reading: "けん", epithet: "The Black Swordsman", rarity: "N", level: 10, style: "eclipse", look: "hulking scarred warrior hefting an impossibly huge slab sword, tattered cloak, prosthetic arm, grim" },
  { id: "ec_witch", name: "Elowen", kanji: "呪", reading: "のろい", epithet: "Hedge Witch of the Marsh", rarity: "R", level: 24, style: "eclipse", look: "hooded young sorceress casting glowing runes, elf companion on shoulder, gnarled staff, misty gothic forest" },
  { id: "ec_apostle", name: "Zodd", kanji: "獣", reading: "けもの", epithet: "Immortal of the Battlefield", rarity: "SR", level: 41, style: "eclipse", look: "towering horned demon-beast warrior with ornate fur and fangs, wings spread, moonlit ruins, chiaroscuro" },
  { id: "ec_eclipse", name: "Nacht", kanji: "蝕", reading: "しょく", epithet: "The Hour of the Eclipse", rarity: "SSR", level: 50, style: "eclipse", look: "ominous crowned godhand silhouette before a blood-red eclipse, swirling hands of the damned, gothic horror" },

  // — chibi —
  { id: "ch_mocha", name: "Mocha", kanji: "豆", reading: "まめ", epithet: "The Snack Gremlin", rarity: "N", level: 1, style: "chibi", look: "tiny round chibi kid hugging an oversized rice ball, huge sparkly eyes, blush, sitting cross-legged" },
  { id: "ch_pud", name: "Pudding", kanji: "甘", reading: "あま", epithet: "Keeper of Desserts", rarity: "N", level: 11, style: "chibi", look: "chibi cat-eared kid balancing a wobbly tower of dango and pudding, tongue out, pastel" },
  { id: "ch_knight", name: "Chibisuke", kanji: "勇", reading: "ゆう", epithet: "The Pocket Hero", rarity: "R", level: 25, style: "chibi", look: "tiny chibi knight in cardboard-looking armor holding a wooden sword and pot-lid shield, brave pose" },
  { id: "ch_dragon", name: "Nibbles", kanji: "竜", reading: "りゅう", epithet: "World's Smallest Dragon", rarity: "SR", level: 40, style: "chibi", look: "chubby chibi baby dragon puffing a tiny smoke ring, sitting on a gold coin, stubby wings, adorable" },
];

export function unlockedCards(level: number): CardDef[] {
  return CARDS.filter((c) => c.level <= level);
}

export function nextUnlock(level: number): CardDef | null {
  return [...CARDS].sort((a, b) => a.level - b.level).find((c) => c.level > level) ?? null;
}

export const RARITY_LABEL: Record<Rarity, string> = {
  N: "Normal",
  R: "Rare",
  SR: "Super Rare",
  SSR: "Spectral Rare",
  UR: "Ultra Rare",
};

export const RARITY_STARS: Record<Rarity, number> = { N: 1, R: 2, SR: 3, SSR: 4, UR: 5 };
