import { log, warn } from "../log";
import { normalize, hasJapanese, matchesTargetScript, getAdapterDirection, setAdapterDirection } from "./util";
import { audioLang, contextLang, normalizeDirection } from "../direction";
import { deriveContentId } from "../cache-key";
import { reportCaptions, resetCaptions } from "../caption-status";
import type { LineContext, SiteAdapter } from "../../types";

interface Cue {
  start: number;
  end: number;
  text: string;
}

interface CaptionTrackMsg {
  videoId: string;
  tracks: { baseUrl: string; languageCode: string; kind: string }[];
}

type OnLine = (text: string, context: LineContext) => void;

/**
 * How long the on-page caption node is treated as untrustworthy after the video
 * changes. YouTube swaps the video before it repaints captions, so for a beat
 * the visible line still belongs to the clip that just ended. Reading it raised
 * a card for the previous video's word (issue #125). One skipped line at the
 * start of a video beats a wrong word.
 */
const CAPTION_SETTLE_MS = 1000;

let onLineCb: OnLine | null = null;

// Hidden caption-track mode: study-language track is fetched and synced to
// playback even while the viewer displays the other language.
let targetCues: Cue[] = [];
let contextCues: Cue[] = [];
/** The video the loaded cues belong to. Compared against the URL's id on every
 * timeupdate: YouTube swaps the video under us on a playlist advance, and the
 * new player response can lag seconds behind, so cues outlive their video. */
let currentVideoId = "";
let lastCueKey = "";
let attachedVideo: HTMLVideoElement | null = null;
let loadedForDirection = "";

function urlVideoId(): string {
  return deriveContentId("youtube") || "";
}

/**
 * Forget cues that belong to a video we are no longer watching.
 *
 * Without this, advancing a playlist kept feeding the previous clip's cues
 * against the new video's clock: cards and the Subtitle Lens showed words from
 * the last video, which is issue #125. Returns true when cues were dropped.
 */
function dropCuesFromOtherVideo(): boolean {
  const id = urlVideoId();
  if (!currentVideoId || !id || id === currentVideoId) return false;
  log("youtube: video changed to", id, "- dropping", targetCues.length, "stale cues");
  targetCues = [];
  contextCues = [];
  lastCueKey = "";
  currentVideoId = "";
  loadedForDirection = "";
  resetCaptions();
  return true;
}

interface Json3Event {
  tStartMs: number;
  dDurMs?: number;
  segs?: { utf8?: string }[];
}

function parseJson3(data: { events?: Json3Event[] }): Cue[] {
  const cues: Cue[] = [];
  for (const ev of data.events || []) {
    if (!ev.segs) continue;
    const text = normalize(ev.segs.map((s) => s.utf8 || "").join(""));
    if (!text) continue;
    const start = ev.tStartMs / 1000;
    cues.push({ start, end: start + (ev.dDurMs || 3000) / 1000, text });
  }
  cues.sort((a, b) => a.start - b.start);
  return cues;
}

async function fetchTrack(track: { baseUrl: string }): Promise<Cue[]> {
  const url = new URL(track.baseUrl, location.origin);
  url.searchParams.set("fmt", "json3");
  const res = await fetch(url.toString());
  if (!res.ok) throw new Error(`timedtext HTTP ${res.status}`);
  const text = await res.text();
  if (!text) return [];
  return parseJson3(JSON.parse(text));
}

function pickTrack(tracks: CaptionTrackMsg["tracks"], langPrefix: string) {
  const matches = tracks.filter((t) => (t.languageCode || "").startsWith(langPrefix));
  return matches.find((t) => t.kind !== "asr") || matches[0] || null;
}

async function handleTracks(msg: CaptionTrackMsg): Promise<void> {
  const direction = getAdapterDirection();
  const dirKey = `${msg.videoId}:${direction}`;
  if (dirKey === currentVideoId + ":" + loadedForDirection && targetCues.length) return;
  currentVideoId = msg.videoId;
  loadedForDirection = direction;
  targetCues = [];
  contextCues = [];
  lastCueKey = "";

  const study = audioLang(direction);
  const ctx = contextLang(direction);
  const studyTrack = pickTrack(msg.tracks, study);
  if (!studyTrack) {
    log(`youtube: no ${study} caption track on this video, DOM fallback only`);
    reportCaptions({ state: "missing", lang: study, reason: "no-track" });
    return;
  }
  try {
    targetCues = await fetchTrack(studyTrack);
  } catch {
    targetCues = [];
  }
  if (!targetCues.length) {
    log(
      `youtube: hidden ${study} caption track unavailable. ` +
        "Use Listening Mode from the toolbar, or turn on matching captions to read them from the page."
    );
    reportCaptions({ state: "missing", lang: study, reason: "empty-track" });
    return;
  }
  log(
    `youtube: loaded ${targetCues.length} ${study} cues (${studyTrack.kind === "asr" ? "auto-generated" : "manual"})`
  );
  reportCaptions({ state: "ok", lang: study, autoGenerated: studyTrack.kind === "asr" });
  const ctxTrack = pickTrack(msg.tracks, ctx);
  if (ctxTrack) {
    try {
      contextCues = await fetchTrack(ctxTrack);
      log(`youtube: loaded ${contextCues.length} ${ctx} cues for context`);
    } catch {
      contextCues = [];
    }
  }
}

function cueAt(cues: Cue[], t: number): Cue | null {
  for (const cue of cues) {
    if (t >= cue.start && t <= cue.end) return cue;
    if (cue.start > t) break;
  }
  return null;
}

function onTimeUpdate(): void {
  if (dropCuesFromOtherVideo()) return;
  if (!targetCues.length || !onLineCb || !attachedVideo) return;
  const t = attachedVideo.currentTime;
  const cue = cueAt(targetCues, t);
  if (!cue) return;
  const key = `${cue.start}:${cue.text}`;
  if (key === lastCueKey) return;
  lastCueKey = key;
  if (!matchesTargetScript(cue.text, getAdapterDirection())) return;
  const ctxCue = cueAt(contextCues, (cue.start + cue.end) / 2);
  onLineCb(cue.text, { en: ctxCue ? ctxCue.text : "" });
}

function getVideo(): HTMLVideoElement | null {
  return document.querySelector<HTMLVideoElement>("#movie_player video, video.html5-main-video");
}

function getVisibleText(): string {
  const segs = document.querySelectorAll(".ytp-caption-segment");
  return normalize(Array.from(segs).map((s) => s.textContent || "").join(" "));
}

export const youtubeAdapter: SiteAdapter = {
  name: "youtube",
  matches() {
    return location.hostname.endsWith("youtube.com");
  },
  getVideo,
  getVisibleText,
  start(onLine) {
    onLineCb = onLine;

    window.addEventListener("message", (e: MessageEvent) => {
      if (e.source !== window) return;
      if (e.data?.source !== "avc" || e.data.type !== "avc-caption-tracks") return;
      handleTracks(e.data as CaptionTrackMsg).catch((err) => warn("youtube tracks error:", err));
    });

    setInterval(() => {
      dropCuesFromOtherVideo();
      const v = getVideo();
      if (v && v !== attachedVideo) {
        if (attachedVideo) attachedVideo.removeEventListener("timeupdate", onTimeUpdate);
        attachedVideo = v;
        v.addEventListener("timeupdate", onTimeUpdate);
      }
    }, 2000);

    let lastText = "";
    let lastTextVideoId = "";
    let settleUntil = 0;
    let debounceTimer: ReturnType<typeof setTimeout> | null = null;

    const check = () => {
      try {
        dropCuesFromOtherVideo();
        if (targetCues.length) return;
        const videoId = urlVideoId();
        if (videoId !== lastTextVideoId) {
          lastTextVideoId = videoId;
          // Bank the line that is on screen at the moment of the change as
          // already-seen: it is the previous video's, and clearing lastText
          // instead would let exactly that line card against the new video.
          lastText = getVisibleText();
          settleUntil = Date.now() + CAPTION_SETTLE_MS;
          return;
        }
        if (Date.now() < settleUntil) return;
        const text = getVisibleText();
        if (!text || text === lastText) return;
        if (!matchesTargetScript(text, getAdapterDirection())) return;
        lastText = text;
        onLine(text, { en: "" });
      } catch (err) {
        warn("youtube adapter error:", err);
      }
    };

    const observer = new MutationObserver(() => {
      if (debounceTimer) clearTimeout(debounceTimer);
      debounceTimer = setTimeout(check, 100);
    });

    observer.observe(document.body, { childList: true, subtree: true, characterData: true });
  },
};

// Re-export for tests / callers that still import hasJapanese from youtube path.
export { hasJapanese, setAdapterDirection, normalizeDirection };
